### ISSUE TITLE
Relate application to mysql router: The MySQL server is running with the --super-read-only option

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/mysql-k8s-bundle#16]
To reproduce:
1. Deploy mysql-k8s-bundle
2. Relate application to mysql-router
3. mysql-k8s leader unit in blocked status with message `Failed to create scoped user`

Snippet of juju debug-log from running `tox -e integration` on https://github.com/canonical/mysql-k8s-bundle/commit/28ddddaa4a272f524064772d30161f5040e6f91c
```
unit-mysql-k8s-0: 20:13:19 WARNING unit.mysql-k8s/0.juju-log database:5: Failed to grant privileges to user relation-5@%
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 491, in _run_mysqlsh_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/pebble.py", line 1307, in wait_output
    raise ExecError(self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['/usr/bin/mysqlsh', '--no-wizard', '--python', '--verbose=1', '-f', '/tmp/script.py', ';', 'rm', '/tmp/script.py'], stdout='', stderr='Cannot set LC_ALL to locale en_US.UTF-8: No such file or directory\nverbose: 2023-01-19T20:13:19Z: Loading startup files...\nverbose: 2023-01-19T20:13:19Z: Loading plugins...\nverbose: 2023-01-19T20:13:19Z: Connecting to MySQL at: clusteradmin@mysql-k8s-0.mysql-k8s-endpoints\nverbose: 2023-01-19T20:13:19Z: Shell.connect: tid=108: CONNECTED: mysql-k8s-0.mysql-k8s-endpoints\nverbose: 2023-01-19T20:13:19Z: Session.run_sql: tid=108: MySQL Error 1290: The MySQL server is running with the --super-read-only option so it cannot execute this statement, SQL: GRANT CREATE USER ON *.* TO \'relation-5\'@\'%\' WITH GRANT OPTION\nTraceback (most recent call last):\n  File "<string>", line 2, in <module>\nmysqlsh.DBError: MySQL Error (1290): Session.run_sql: The MySQL server is running with the --super-read-only option so it cannot execute this statement\n'
```

<details>
<summary>Full tox output:</summary>

```
ubuntu@dev-env-2:~/repos/mysql-k8s-bundle$ tox -e integration 
integration: commands[0]> pytest -v --tb native --ignore=/home/ubuntu/repos/mysql-k8s-bundle/tests/unit --log-cli-level=INFO -s --durations=0
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.10.6, pytest-7.2.1, pluggy-1.0.0 -- /home/ubuntu/repos/mysql-k8s-bundle/.tox/integration/bin/python
cachedir: .tox/integration/.pytest_cache
rootdir: /home/ubuntu/repos/mysql-k8s-bundle, configfile: pyproject.toml
plugins: operator-0.23.0, asyncio-0.20.3
asyncio: mode=auto
collected 2 items                                                                                                                                                         

tests/integration/test_bundle.py::test_deploy_bundle 
----------------------------------------------------------------------------- live log setup ------------------------------------------------------------------------------
INFO     pytest_operator.plugin:plugin.py:618 Adding model micro:test-bundle-8z98 on cloud microk8s
------------------------------------------------------------------------------ live log call ------------------------------------------------------------------------------
INFO     juju.bundle:bundle.py:384 Applying change: upload charm mysql-k8s from channel latest/edge
INFO     juju.bundle:bundle.py:384 Applying change: upload charm mysql-router-k8s from channel latest/edge
INFO     juju.bundle:bundle.py:384 Applying change: upload charm tls-certificates-operator from channel latest/edge
INFO     juju.bundle:bundle.py:384 Applying change: deploy application mysql-k8s with 3 units using $addCharm-0
INFO     juju.model:model.py:1928 Deploying ch:amd64/jammy/mysql-k8s-30
INFO     juju.bundle:bundle.py:384 Applying change: deploy application mysql-router-k8s with 1 unit using $addCharm-3
INFO     juju.model:model.py:1928 Deploying ch:amd64/jammy/mysql-router-k8s-6
INFO     juju.bundle:bundle.py:384 Applying change: deploy application tls-certificates-operator with 1 unit using $addCharm-6
INFO     juju.model:model.py:1928 Deploying ch:amd64/focal/tls-certificates-operator-20
INFO     juju.bundle:bundle.py:384 Applying change: add relation $deploy-1:certificates - $deploy-7:certificates
INFO     juju.bundle:bundle.py:902 Relating mysql-k8s:certificates <-> tls-certificates-operator:certificates
INFO     juju.bundle:bundle.py:384 Applying change: add relation $deploy-1:database - $deploy-4:backend-database
INFO     juju.bundle:bundle.py:902 Relating mysql-k8s:database <-> mysql-router-k8s:backend-database
INFO     juju.bundle:bundle.py:384 Applying change: set annotations for $deploy-1
INFO     juju.bundle:bundle.py:384 Applying change: set annotations for $deploy-4
INFO     juju.bundle:bundle.py:384 Applying change: set annotations for $deploy-7
INFO     juju.model:model.py:2530 Waiting for model:
  mysql-k8s/0 [allocating] waiting: installing agent
  mysql-k8s/1 [allocating] waiting: installing agent
  mysql-k8s/2 [allocating] waiting: installing agent
  tls-certificates-operator/0 [allocating] waiting: installing agent
INFO     juju.model:model.py:2530 Waiting for model:
  mysql-k8s/0 [executing] maintenance: installing charm software
  mysql-k8s/1 [executing] maintenance: installing charm software
  mysql-k8s/2 [executing] maintenance: installing charm software
  tls-certificates-operator/0 [executing] maintenance: installing charm software
INFO     juju.model:model.py:2530 Waiting for model:
  mysql-k8s/0 [executing] maintenance: Initialising mysqld
  mysql-k8s/1 [executing] maintenance: Initialising mysqld
  mysql-k8s/2 [idle] maintenance: Initialising mysqld
  tls-certificates-operator/0 [idle] active: 
INFO     juju.model:model.py:2530 Waiting for model:
  mysql-k8s/0 [executing] active: Unit is ready: Mode: RW
  mysql-k8s/1 [idle] waiting: Waiting for instance to join the cluster
  mysql-k8s/2 [idle] waiting: Waiting for instance to join the cluster
  tls-certificates-operator/0 [idle] active: 
INFO     juju.model:model.py:2530 Waiting for model:
  mysql-k8s/0 [executing] active: Unit is ready: Mode: RW
  mysql-k8s/1 [idle] waiting: Awaiting restart operation
  mysql-k8s/2 [idle] waiting: Waiting for instance to join the cluster
INFO     juju.model:model.py:2530 Waiting for model:
  mysql-k8s/0 [executing] active: Unit is ready: Mode: RW
  mysql-k8s/1 [executing] active: 
  mysql-k8s/2 [executing] active: Unit is ready: Mode: RO
  tls-certificates-operator/0 [idle] active: 
INFO     juju.model:model.py:2530 Waiting for model:
  mysql-k8s/0 [idle] active: Unit is ready: Mode: RW
  mysql-k8s/1 [executing] maintenance: Executing restart operation
  mysql-k8s/2 [idle] active: Unit is ready: Mode: RO
INFO     juju.model:model.py:2530 Waiting for model:
  mysql-k8s/0 [idle] active: 
  mysql-k8s/1 [idle] active: Unit is ready: Mode: RO
  mysql-k8s/2 [idle] active: Unit is ready: Mode: RW
INFO     juju.model:model.py:2530 Waiting for model:
  mysql-router-k8s/0 [idle] waiting: 
PASSED
tests/integration/test_bundle.py::test_mysql_primary_switchover 
------------------------------------------------------------------------------ live log call ------------------------------------------------------------------------------
INFO     pytest_operator.plugin:plugin.py:497 Using tmp_path: /home/ubuntu/repos/mysql-k8s-bundle/.tox/integration/tmp/pytest/test-bundle-8z980
INFO     pytest_operator.plugin:plugin.py:941 Building charm application
INFO     pytest_operator.plugin:plugin.py:946 Built charm application in 32.45s
INFO     juju.model:model.py:1928 Deploying local:focal/application-0
INFO     juju.model:model.py:2530 Waiting for model:
  mysql-k8s/0 [idle] active: Unit is ready: Mode: RO
  mysql-k8s/1 [idle] active: Unit is ready: Mode: RO
  mysql-k8s/2 [idle] active: Unit is ready: Mode: RW
  mysql-router-k8s/0 [idle] waiting: 
  application/0 [allocating] waiting: installing agent
FAILED
---------------------------------------------------------------------------- live log teardown ----------------------------------------------------------------------------
INFO     pytest_operator.plugin:plugin.py:761 Model status:

Model             Controller  Cloud/Region        Version  SLA          Timestamp
test-bundle-8z98  micro       microk8s/localhost  2.9.29   unsupported  20:13:21Z

App                        Version                  Status   Scale  Charm                      Channel  Rev  Address        Exposed  Message
application                                         waiting      1  application                           0  10.152.183.43  no       installing agent
mysql-k8s                  8.0.31-0ubuntu0.22.04.1  active       3  mysql-k8s                  edge      30  10.152.183.93  no       
mysql-router-k8s                                    waiting      1  mysql-router-k8s           edge       6  10.152.183.95  no       installing agent
tls-certificates-operator                           active       1  tls-certificates-operator  edge      20  10.152.183.85  no       

Unit                          Workload  Agent      Address       Ports  Message
application/0*                waiting   idle       10.1.198.226         
mysql-k8s/0*                  blocked   idle       10.1.198.241         Failed to create scoped user
mysql-k8s/1                   active    idle       10.1.198.251         Unit is ready: Mode: RO
mysql-k8s/2                   active    idle       10.1.198.223         Unit is ready: Mode: RW
mysql-router-k8s/0*           waiting   executing  10.1.198.252         
tls-certificates-operator/0*  active    idle       10.1.198.239         


INFO     pytest_operator.plugin:plugin.py:767 Juju error logs:

controller-0: 20:08:34 ERROR juju.worker.caasapplicationprovisioner.runner exited "mysql-k8s": Operation cannot be fulfilled on pods "mysql-k8s-0": the object has been modified; please apply your changes to the latest version and try again

INFO     pytest_operator.plugin:plugin.py:786 juju-crashdump command was not found.
INFO     pytest_operator.plugin:plugin.py:854 Resetting model test-bundle-8z98...
INFO     pytest_operator.plugin:plugin.py:843    Destroying applications mysql-k8s
INFO     pytest_operator.plugin:plugin.py:843    Destroying applications mysql-router-k8s
INFO     pytest_operator.plugin:plugin.py:843    Destroying applications tls-certificates-operator
INFO     pytest_operator.plugin:plugin.py:843    Destroying applications application
INFO     pytest_operator.plugin:plugin.py:859 Not waiting on reset to complete.
INFO     pytest_operator.plugin:plugin.py:832 Forgetting main...


================================================================================ FAILURES =================================================================================
______________________________________________________________________ test_mysql_primary_switchover ______________________________________________________________________
Traceback (most recent call last):
  File "/home/ubuntu/repos/mysql-k8s-bundle/tests/integration/test_bundle.py", line 47, in test_mysql_primary_switchover
    await ops_test.model.wait_for_idle(
  File "/home/ubuntu/repos/mysql-k8s-bundle/.tox/integration/lib/python3.10/site-packages/juju/model.py", line 2523, in wait_for_idle
    _raise_for_status(blocks, "blocked")
  File "/home/ubuntu/repos/mysql-k8s-bundle/.tox/integration/lib/python3.10/site-packages/juju/model.py", line 2465, in _raise_for_status
    raise error_type("{}{} in {}: {}".format(
juju.errors.JujuUnitError: Unit in blocked: mysql-k8s/0
---------------------------------------------------------------------------- Captured log call ----------------------------------------------------------------------------
INFO     pytest_operator.plugin:plugin.py:497 Using tmp_path: /home/ubuntu/repos/mysql-k8s-bundle/.tox/integration/tmp/pytest/test-bundle-8z980
INFO     pytest_operator.plugin:plugin.py:941 Building charm application
INFO     pytest_operator.plugin:plugin.py:946 Built charm application in 32.45s
INFO     juju.model:model.py:1928 Deploying local:focal/application-0
INFO     juju.model:model.py:2530 Waiting for model:
  mysql-k8s/0 [idle] active: Unit is ready: Mode: RO
  mysql-k8s/1 [idle] active: Unit is ready: Mode: RO
  mysql-k8s/2 [idle] active: Unit is ready: Mode: RW
  mysql-router-k8s/0 [idle] waiting: 
  application/0 [allocating] waiting: installing agent
-------------------------------------------------------------------------- Captured log teardown --------------------------------------------------------------------------
INFO     pytest_operator.plugin:plugin.py:761 Model status:

Model             Controller  Cloud/Region        Version  SLA          Timestamp
test-bundle-8z98  micro       microk8s/localhost  2.9.29   unsupported  20:13:21Z

App                        Version                  Status   Scale  Charm                      Channel  Rev  Address        Exposed  Message
application                                         waiting      1  application                           0  10.152.183.43  no       installing agent
mysql-k8s                  8.0.31-0ubuntu0.22.04.1  active       3  mysql-k8s                  edge      30  10.152.183.93  no       
mysql-router-k8s                                    waiting      1  mysql-router-k8s           edge       6  10.152.183.95  no       installing agent
tls-certificates-operator                           active       1  tls-certificates-operator  edge      20  10.152.183.85  no       

Unit                          Workload  Agent      Address       Ports  Message
application/0*                waiting   idle       10.1.198.226         
mysql-k8s/0*                  blocked   idle       10.1.198.241         Failed to create scoped user
mysql-k8s/1                   active    idle       10.1.198.251         Unit is ready: Mode: RO
mysql-k8s/2                   active    idle       10.1.198.223         Unit is ready: Mode: RW
mysql-router-k8s/0*           waiting   executing  10.1.198.252         
tls-certificates-operator/0*  active    idle       10.1.198.239         


INFO     pytest_operator.plugin:plugin.py:767 Juju error logs:

controller-0: 20:08:34 ERROR juju.worker.caasapplicationprovisioner.runner exited "mysql-k8s": Operation cannot be fulfilled on pods "mysql-k8s-0": the object has been modified; please apply your changes to the latest version and try again

INFO     pytest_operator.plugin:plugin.py:786 juju-crashdump command was not found.
INFO     pytest_operator.plugin:plugin.py:854 Resetting model test-bundle-8z98...
INFO     pytest_operator.plugin:plugin.py:843    Destroying applications mysql-k8s
INFO     pytest_operator.plugin:plugin.py:843    Destroying applications mysql-router-k8s
INFO     pytest_operator.plugin:plugin.py:843    Destroying applications tls-certificates-operator
INFO     pytest_operator.plugin:plugin.py:843    Destroying applications application
INFO     pytest_operator.plugin:plugin.py:859 Not waiting on reset to complete.
INFO     pytest_operator.plugin:plugin.py:832 Forgetting main...
============================================================================ slowest durations ============================================================================
260.92s call     tests/integration/test_bundle.py::test_deploy_bundle
60.50s call     tests/integration/test_bundle.py::test_mysql_primary_switchover
4.61s teardown tests/integration/test_bundle.py::test_mysql_primary_switchover
0.73s setup    tests/integration/test_bundle.py::test_deploy_bundle

(2 durations < 0.005s hidden.  Use -vv to show these durations.)
========================================================================= short test summary info =========================================================================
FAILED tests/integration/test_bundle.py::test_mysql_primary_switchover - juju.errors.JujuUnitError: Unit in blocked: mysql-k8s/0
================================================================= 1 failed, 1 passed in 326.85s (0:05:26) =================================================================
integration: exit 1 (328.67 seconds) /home/ubuntu/repos/mysql-k8s-bundle> pytest -v --tb native --ignore=/home/ubuntu/repos/mysql-k8s-bundle/tests/unit --log-cli-level=INFO -s --durations=0 pid=1917429
  integration: FAIL code 1 (328.73=setup[0.06]+cmd[328.67] seconds)
  evaluation failed :( (328.78 seconds)
```
</details>

Replicated using `tests/integration/application_charm` from https://github.com/canonical/mysql-k8s-operator and `tests/integration/application-charm` from https://github.com/canonical/mysql-router-k8s-operator

<details>
<summary>Replicated on charmhub revisions:</summary>

mysql-k8s: 30
mysql-router-k8s: 6
tls-certificates-operator: 20

mysql-k8s: 30
mysql-router-k8s: 6
tls-certificates-operator: 19

mysql-k8s: 30
mysql-router-k8s: 6
tls-certificates-operator: 13

mysql-k8s: 30
mysql-router-k8s: 6
tls-certificates-operator: 16

mysql-k8s: 24
mysql-router-k8s: 5
tls-certificates-operator: 19
</details>

**Comment by taurus-forever** [comment]
The backlog bugreport created to pickup the next sprint: https://warthogs.atlassian.net/browse/DPE-1139
